[package]
name = "cboe-pitch-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
uuid = "1.8"
